language: php
php:
  - "5.5"
env:
 - DB=mysqli
 - DB=pgsql
 - HHVM=true
 - HHVM=false

before_install:
  - if [[ $HHVM == true && `phpenv global` == "5.5" ]] ; then IS_HHVM_JOB=true ; else IS_HHVM_JOB=false ; fi
  - if [[ $HHVM == false ]] ; then IS_PHP_JOB=true ; else IS_PHP_JOB=false ; fi
  - if [[ $IS_HHVM_JOB == true ]] ; then sudo bin/install_hhvm; fi

before_script:
  - pear channel-discover pear.phpunit.de
  - pear channel-discover pear.symfony.com
  - pear install pear.phpunit.de/DbUnit
  - phpenv rehash
  - cp config-dist.php config.php
  - sh -c "sed -i -e s/'password'/''/ -e s/example.com/localhost/ -e s%/home/example%$HOME% -e 's%\(\$CFG.*phpu\)%\n\1%' config.php"
  - sh -c "if [ '$DB' = 'mysqli' ]; then mysql -e 'create database moodle default character set UTF8 collate UTF8_bin;'; fi"
  - sh -c "if [ '$DB' = 'mysqli' ]; then sed -i -e s/\'pgsql\'/\'mysqli\'/ -e s/\'username\'/\'root\'/ config.php; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database moodle;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'pgsql' ]; then sed -i s/\'username\'/\'postgres\'/ config.php; fi"
  - mkdir -m777 $HOME/moodledata
  - if [[ $IS_PHP_JOB == true ]]  ; then php admin/tool/phpunit/cli/init.php ; fi
  - if [[ $IS_HHVM_JOB == true ]] ; then hhvm admin/tool/phpunit/cli/init.php ; fi

script:
  - if [[ $IS_PHP_JOB == true ]]  ; then php phpunit.php  ; fi
  - if [[ $IS_HHVM_JOB == true ]] ; then hhvm phpunit.php ; fi

notifications:
  email:
    - david.scotson@gla.ac.uk
