version: "3.5"
services:
  webserver:
    image: "moodlehq/moodle-php-apache:7.4"
    depends_on:
      - db
    volumes:
      - .:/var/www/html:cached
      - "./apache2_faildumps.conf:/etc/apache2/conf-enabled/apache2_faildumps.conf"
      - "./apache2_mailhog.conf:/etc/apache2/conf-enabled/apache2_mailhog.conf"
    environment:
      MOODLE_DOCKER_DBTYPE: mysqli
      MOODLE_DOCKER_DBCOLLATION: utf8mb4_bin
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_DBPASS: "m@0dl3ing"
      MOODLE_DOCKER_BROWSER: firefox
      MOODLE_DOCKER_WEB_HOST: "moodle.localhost"
      TRAEFIK_DOMAIN: moodle.localhost
      TRAEFIK_SUBDOMAIN:
    labels:
      traefik.enable: "true"
      traefik.http.routers.elearning-apache.rule:
          ' HostRegexp(`{subdomain:.+}.${TRAEFIK_DOMAIN}`)
          || Host(`${TRAEFIK_DOMAIN}`)'
      traefik.http.routers.elearning-apache.tls: "true"
      traefik.http.services.elearning-apache.loadbalancer.server.port: '80'
  db:
    image: mysql:5
    command: >
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_bin
            --innodb_file_format=barracuda
            --innodb_file_per_table=On
            --innodb_large_prefix=On
    environment:
      MYSQL_ROOT_PASSWORD: "m@0dl3ing"
      MYSQL_USER: moodle
      MYSQL_PASSWORD: "m@0dl3ing"
      MYSQL_DATABASE: moodle
