name: Run Moodle

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 build:
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Setup PHP
     uses: shivammathur/setup-php@v2
     with:
       php-version: '7.4'
       extensions: mbstring, intl, gd, xml, mysql, mysqli, zip, bcmath, curl
       coverage: xdebug

   - name: Install dependencies
     run: |
       sudo apt-get install -y unzip
       wget https://download.moodle.org/download.php/direct/stable310/moodle-latest-310.tgz
       tar -xvf moodle-latest-310.tgz
       mv moodle/* .
       rm -rf moodle moodle-latest-310.tgz

   - name: Setup MySQL
     uses: jwilder/setup-mysql@v1
     with:
       mysql-version: '5.7'
       mysql-database: 'moodle'
       mysql-user: 'moodle'
       mysql-password: 'moodle'

   - name: Start Moodle
     run: |
       php -S localhost:8000
