name: Run Moodle

on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 build:
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Setup PHP
     uses: shivammathur/setup-php@v2
     with:
       php-version: '7.4'
       extensions: mbstring, intl, gd, xml, pgsql, mysqli, zip, bcmath, curl
       coverage: xdebug

   - name: Cache Moodle
     uses: actions/cache@v2
     with:
       path: moodle
       key: ${{ runner.os }}-moodle-${{ hashFiles('**/moodle-latest-310.tgz') }}
       restore-keys: |
         ${{ runner.os }}-moodle-

   - name: Install dependencies
     run: |
       sudo apt-get install -y unzip rsync
       wget https://download.moodle.org/download.php/direct/stable310/moodle-latest-310.tgz
       tar -xvf moodle-latest-310.tgz
       rsync -av --progress moodle/* .
       rm -rf moodle moodle-latest-310.tgz

   - name: Start Moodle
     run: |
       php -S localhost:8000

